version: '3.5'
networks:  
  ms-network:  
    name: ms-network  
    driver: bridge
services:
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    networks:
      - ms-network
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  car-data-service:
    image: car-data-service
    container_name: car-data-service
    networks:
      - ms-network
    build:
      context: ./car-data-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      server.port: 8082
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
    links:
      - eureka-server

  customer-service:
    image: customer-service
    container_name: customer-service
    networks:
      - ms-network
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    environment:
      server.port: 8083
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
    links:
      - eureka-server

  lease-rate:
    image: lease-rate
    container_name: lease-rate
    networks:
      - ms-network
    build:
      context: ./lease-rate
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    environment:
      server.port: 8084
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
    links:
      - eureka-server
