management:
  endpoints:
    web:
      exposure:
        include: '*'
    routes:
      enabled: 'true'
fetchRegistry: 'true'
spring:
  application:
    name: customersss-service
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    initialization-mode: always
    url: jdbc:h2:mem:customerdb
  cloud:
    config:
      import-check:
        enabled: 'false'
      uri: http://localhost:8888
      name: database
  management:
    security:
      enabled: 'false'
  h2:
    console:
      enabled: 'true'
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
registerWithEureka: 'true'
server:
  port: '8082'
defaultZone: http://localhost:8761/eureka/
preferIpAddress: 'true'
