fetchRegistry: 'true'
spring:
  application:
    name: lease-rate-service
  cloud:
    config:
      import-check:
        enabled: 'false'
registerWithEureka: 'true'
server:
  port: '8084'
defaultZone: http://localhost:8761/eureka/
